### PR TITLE
Consolidate Actions.Core dependencies

### PR DESCRIPTION
**Pull request by fredrikhr**
Currently the `Action.Core` package depends on the `Actions.Octokit` package, despite it not using anything from the Octokit package (except for constants for environment variables).

This PR splits the `EnvironmentKeys` namespace and moved the variables used by Core into the `Core` package and leaves the ones used by Octokit in the `Octokit` package.

An alternate design would be to simply move the `EnvironmentVariables` namespace over to the `Core` package in its entirety and making `Octokit` depend on `Core` instead. Personally, I would actually prefer this alternative.

I'd also prefer to align the `EnvironmentVariables.Keys` class with all the keys listed on the official GitHub Actions documentation: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

I am happy to modify the PR to include the alternate design and/or include the missing keys from the documentation if desired.

### CODE REVIEW

**Comment by IEvangelist** [comment]
This is great, thank you so much for this! Yeah, I'd love for the addition of the missing env vars as well. Thanks again @fredrikhr

**Comment by IEvangelist** [comment]
@all-contributors please add @fredrikhr for code and ideas

**Comment by fredrikhr** [comment]
@IEvangelist do you think we should move the Environment keys namespace over to the Core package in its entirety or do you think the split with some in Octokit and some in Core is better?

I'll add the commit with additional keys shortly.

**Comment by IEvangelist** [comment]
> @IEvangelist do you think we should move the Environment keys namespace over to the Core package in its entirety or do you think the split with some in Octokit and some in Core is better?
> 
> I'll add the commit with additional keys shortly.

@fredrikhr - I'm thinking it might make sense to have one new package that contains some of these shared bits (starting with the env vars), so that it's all in one place and then any package can consume them. What do you think?

**Comment by fredrikhr** [comment]
Hmm, I don't think that an extra assembly for just constants is warrented.

If all environment variables were moved to the Core package Octokit would have to depend on Core. But not really, since the constants are all embedded compile-time, the dependency is compile-time only (the Core assembly will not be required at runtime).

In https://github.com/IEvangelist/dotnet-github-actions-sdk/pull/13/commits/70548dfbe23c75729a38f7f3d9da977114945f21 I have created a compile-time constant that defines the EnvironmentVariables classes as either `public` or `internal` classes. That way the Octokit package will remain without dependency on Core, but it will carry all the required constants in its assembly. (Internal is to avoid ambiguities for consumers that want to consume both Core and Octokit)

Alternatively Octokit could be made to `<ProjectReference>` the Core package, but set the `<PrivateAssets>all</PrivateAssets>` metadata, thus avoiding the dependency to be published (thus mating it a compile-time dependency for Nuget purposes). This accomplishes the same as the trick I did above, but is more dangerous for future development as one has to take care to really only relying on constants (and nothing else).

**Comment by IEvangelist** [comment]
I really like this, thank you so much for these changes! I don't often use the embedded compile-time bits like that, I usually forget it's an option. I do like it here though. Let's :shipit:.

**Pull request merged**
